import AlphaZero
#include("game.jl")
#g = GI.read_state(Game)
#g = GI.init(GameSpec())
#update_status!(g)
# GI.render(g)
#print(" Move: ")
#a = GI.parse_action(g, readline())
# a = GI.parse_action(g, "8c*n")
# GI.play!(g, GI.parse_action(g, "00/s"))
# GI.render(g)
# GI.play!(g, GI.parse_action(g, "44/n"))
# GI.render(g)
# GI.play!(g, GI.parse_action(g, "80/n"))
# GI.render(g)
# GI.play!(g, GI.parse_action(GI.spec(g), "40/e"))
# GI.render(g)
# GI.render(GI.play!(g, GI.parse_action(g, "0c*e")))
AlphaZero.Scripts.test_game("bonbon-rectangle")